# Generated by Django 4.1.1 on 2023-05-04 00:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_atividademodel_data'),
    ]

    operations = [
        migrations.AlterField(
            model_name='atividademodel',
            name='data',
            field=models.DateTimeField(default=2000, verbose_name='Data'),
        ),
    ]
