# Generated by Django 4.1.1 on 2023-05-04 00:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_atividademodel_data'),
    ]

    operations = [
        migrations.AlterField(
            model_name='atividademodel',
            name='data',
            field=models.DateTimeField(auto_now=True, verbose_name='Data'),
        ),
    ]
