# Generated by Django 4.1.1 on 2023-05-04 00:27

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_alter_atividademodel_data'),
    ]

    operations = [
        migrations.AlterField(
            model_name='atividademodel',
            name='data',
            field=models.DateField(default=datetime.datetime(2023, 5, 4, 0, 27, 40, 583231, tzinfo=datetime.timezone.utc), verbose_name='Data'),
        ),
    ]
