# Generated by Django 4.1.9 on 2023-05-06 21:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_alter_atividademodel_data_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='atividademodel',
            name='data',
            field=models.DateField(verbose_name='Data'),
        ),
    ]
